datamodule:
  _target_: "SLAE.datasets.pnunits_datamodule.PNUnitsDataModule"   # <-- Make sure import path matches where you put the class

  # -------------------------------------------------------------------------
  # Dataset sources
  # -------------------------------------------------------------------------
  train_parquet: "/data/metadata/new_pn_units_df.parquet" # Path to training parquet file, see atomworks docs
  val_parquet:   "/data/metadata/new_pn_units_df.parquet" # Path to validation parquet file

  pdb_mirror_path: "/data/pdb/" # Path to local PDB mirror
  # -------------------------------------------------------------------------
  # Batch + sampling
  # -------------------------------------------------------------------------
  batch_size: 12
  train_samples_per_epoch: 10000
  val_samples_per_epoch:   2000

  crop_size: 512

  # -------------------------------------------------------------------------
  # DataLoader configuration
  # -------------------------------------------------------------------------
  num_workers: 8
  pin_memory: False

  # These correspond to the ProteinDataLoader internal collater:
  follow_batch: []
  exclude_keys: []

num_classes: 24 # Number of classes