# @package _global_

# === 1. Set config parameters ===
name: "AutoEncoder_train" # default name for the experiment, "" means logger (eg. wandb) will generate a unique name
seed: 42 # seed for random number generators in pytorch, numpy and python.random
num_workers: 4 # number of subprocesses to use for data loading.

# === 2. Specify defaults here. Defaults will be overwritten by equivalently named options in this file ===
defaults:
  - env: default
  - dataset: pdb
  - features: fa #full_atom
  - encoder: protein_encoder
  - decoder: allatom_decoder
  - callbacks: default
  - optimiser: adamw
  - scheduler: linear_warmup_cosine_decay
  - trainer: gpu
  - hydra: default
  - metrics: 
    - rmse
    - accuracy
  - task: eng_struct_pretrain
  - logger: wandb 
  - _self_ # see: https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order/. Adding _self_ at bottom means values in this file override defaults.

task_name: "train"
test: true
#compile: True
