_wandb:
    value:
        cli_version: 0.23.1
        e:
            ty7dacytku596inc66qho3hh9i9redx6:
                args:
                    - --train_list
                    - splits/train_test.txt
                    - --val_list
                    - splits/valid_test.txt
                    - --freeze_encoder
                    - --epochs
                    - "100"
                    - --batch_size
                    - "1"
                    - --wandb_project
                    - flow_single_test
                codePath: scripts/train.py
                codePathLocal: train.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "75094818816"
                        used: "30862848000"
                email: vratins@andrew.cmu.edu
                executable: /home/srivasv/WaterFlow/.venv/bin/python3
                git:
                    commit: 49f7fa542bbed3fd226fa28c94b222136dc2ee8d
                    remote: git@github.com:Wankowicz-Lab/WaterFlow.git
                gpu: NVIDIA H100 NVL
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-0c165662-d3b1-861e-6ffc-8a81b965ff63
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-a2e831dd-3a9d-cb64-ca4a-dba6629429c6
                host: everest.csb.vanderbilt.edu
                memory:
                    total: "236293079040"
                os: Linux-5.14.0-570.19.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: /home/srivasv/WaterFlow/scripts/train.py
                python: CPython 3.12.10
                root: /home/srivasv/WaterFlow/scripts
                startedAt: "2025-12-18T16:58:25.746481Z"
                writerId: ty7dacytku596inc66qho3hh9i9redx6
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 16
            "4": 3.12.10
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
base_pdb_dir:
    value: /sb/wankowicz_lab/data/srivasv/pdb_redo_data
batch_size:
    value: 1
device:
    value: cuda
encoder_ckpt:
    value: null
epochs:
    value: 100
eval_every:
    value: 5
flow_layers:
    value: 4
freeze_encoder:
    value: true
grad_clip:
    value: 1
hidden_s:
    value: 256
hidden_v:
    value: 64
k_pw:
    value: 12
k_ww:
    value: 12
lr:
    value: 0.001
n_eval_samples:
    value: 3
num_workers:
    value: 4
p_distort:
    value: 0.2
p_self_cond:
    value: 0.5
processed_dir:
    value: /home/srivasv/flow_cache/
rk4_steps:
    value: 100
save_dir:
    value: /home/srivasv/flow_checkpoints
save_every:
    value: 10
sigma_distort:
    value: 0.5
t_distort:
    value: 0.5
train_list:
    value: splits/train_test.txt
use_distortion:
    value: false
use_self_cond:
    value: false
val_list:
    value: splits/valid_test.txt
wandb_project:
    value: flow_single_test
wandb_run:
    value: null
weight_decay:
    value: 0.0001
