"""
Quality control script for symmetry mates. Completely generated by claude code and lightly edited.

This script checks:
1. Are mates being generated correctly by PyMOL?
2. Are mate atoms actually near ASU (within cutoff)?
3. Are the right number of mates generated?
4. Visualize ASU + mates for manual inspection

Usage:
    python scripts/qc_symmetry_mates.py \
        --processed_dir /path/to/cache \
        --base_pdb_dir /path/to/pdbs \
        --num_samples 5 \
        --output_dir qc_mates
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# For re-running mate detection
import pymol2
import torch
from loguru import logger
from mpl_toolkits.mplot3d import Axes3D
from tqdm import tqdm

from src.dataset import get_crystal_contacts_pymol


def analyze_mate_distances(cached_data, cutoff=5.0):
    """
    Analyze distances between ASU and symmetry mates.

    Returns:
        dict with statistics about mate distances
    """
    protein_pos = cached_data['protein_pos'].numpy()
    mate_pos = cached_data['mate_pos'].numpy()

    if mate_pos.shape[0] == 0:
        return {
            'num_mates': 0,
            'min_dist': None,
            'max_dist': None,
            'mean_dist': None,
            'within_cutoff': 0,
        }

    # Compute pairwise distances between ASU and mates
    # This is expensive for large structures, so we sample
    n_asu = min(protein_pos.shape[0], 1000)
    n_mate = min(mate_pos.shape[0], 1000)

    asu_sample = protein_pos[np.random.choice(protein_pos.shape[0], n_asu, replace=False)]
    mate_sample = mate_pos[np.random.choice(mate_pos.shape[0], n_mate, replace=False)]

    # Compute distances
    dists = np.linalg.norm(asu_sample[:, None] - mate_sample[None, :], axis=-1)
    min_dists_per_mate = dists.min(axis=0)

    return {
        'num_mates': mate_pos.shape[0],
        'num_asu': protein_pos.shape[0],
        'min_dist': float(min_dists_per_mate.min()),
        'max_dist': float(min_dists_per_mate.max()),
        'mean_dist': float(min_dists_per_mate.mean()),
        'median_dist': float(np.median(min_dists_per_mate)),
        'within_cutoff': int((min_dists_per_mate <= cutoff).sum()),
        'percent_within_cutoff': float((min_dists_per_mate <= cutoff).sum() / len(min_dists_per_mate) * 100),
    }


def visualize_mates(cached_data, pdb_id, output_dir):
    """
    Create 3D visualization of ASU + mates.

    Saves plot to output_dir.
    """
    protein_pos = cached_data['protein_pos'].numpy()
    mate_pos = cached_data['mate_pos'].numpy()
    water_pos = cached_data['water_pos'].numpy()

    fig = plt.figure(figsize=(12, 10))
    ax = fig.add_subplot(111, projection='3d')

    # Subsample for visualization
    n_asu_viz = min(protein_pos.shape[0], 500)
    n_mate_viz = min(mate_pos.shape[0], 500)
    n_water_viz = min(water_pos.shape[0], 100)

    asu_viz = protein_pos[np.random.choice(protein_pos.shape[0], n_asu_viz, replace=False)]
    if mate_pos.shape[0] > 0:
        mate_viz = mate_pos[np.random.choice(mate_pos.shape[0], n_mate_viz, replace=False)]
    else:
        mate_viz = np.zeros((0, 3))

    if water_pos.shape[0] > 0:
        water_viz = water_pos[np.random.choice(water_pos.shape[0], n_water_viz, replace=False)]
    else:
        water_viz = np.zeros((0, 3))

    # Plot ASU (blue), mates (red), waters (cyan)
    ax.scatter(asu_viz[:, 0], asu_viz[:, 1], asu_viz[:, 2],
               c='blue', marker='o', s=20, alpha=0.6, label=f'ASU ({protein_pos.shape[0]} atoms)')

    if mate_viz.shape[0] > 0:
        ax.scatter(mate_viz[:, 0], mate_viz[:, 1], mate_viz[:, 2],
                   c='red', marker='^', s=20, alpha=0.6, label=f'Mates ({mate_pos.shape[0]} atoms)')

    if water_viz.shape[0] > 0:
        ax.scatter(water_viz[:, 0], water_viz[:, 1], water_viz[:, 2],
                   c='cyan', marker='*', s=10, alpha=0.4, label=f'Waters ({water_pos.shape[0]})')

    ax.set_xlabel('X (Å)')
    ax.set_ylabel('Y (Å)')
    ax.set_zlabel('Z (Å)')
    ax.set_title(f'{pdb_id} - ASU + Symmetry Mates')
    ax.legend()

    # Equal aspect ratio
    max_range = np.array([asu_viz.max(axis=0) - asu_viz.min(axis=0)]).max() / 2.0
    mid_x = (asu_viz[:, 0].max() + asu_viz[:, 0].min()) * 0.5
    mid_y = (asu_viz[:, 1].max() + asu_viz[:, 1].min()) * 0.5
    mid_z = (asu_viz[:, 2].max() + asu_viz[:, 2].min()) * 0.5
    ax.set_xlim(mid_x - max_range, mid_x + max_range)
    ax.set_ylim(mid_y - max_range, mid_y + max_range)
    ax.set_zlim(mid_z - max_range, mid_z + max_range)

    output_path = Path(output_dir) / f"{pdb_id}_mates.png"
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    plt.close()

    logger.info(f"  Saved visualization to {output_path}")


def compare_mate_detection(pdb_path, cache_path, cutoff=5.0):
    """
    Re-run mate detection and compare with cached results.

    Returns:
        dict with comparison statistics
    """
    # Load cached mates
    cached = torch.load(cache_path, weights_only=False)
    cached_mate_pos = cached['mate_pos'].numpy()

    # Re-run PyMOL mate detection
    crystal_data = get_crystal_contacts_pymol(str(pdb_path), cutoff=cutoff)
    fresh_mate_coords = crystal_data['mate_coords']

    return {
        'cached_num_mates': cached_mate_pos.shape[0],
        'fresh_num_mates': fresh_mate_coords.shape[0],
        'match': cached_mate_pos.shape[0] == fresh_mate_coords.shape[0],
    }


def main():
    parser = argparse.ArgumentParser(description="QC symmetry mates")
    parser.add_argument("--processed_dir", type=str, required=True)
    parser.add_argument("--base_pdb_dir", type=str,
                       default="/sb/wankowicz_lab/data/srivasv/pdb_redo_data")
    parser.add_argument("--num_samples", type=int, default=10,
                       help="Number of samples to analyze in detail")
    parser.add_argument("--output_dir", type=str, default="qc_mates")
    parser.add_argument("--cutoff", type=float, default=5.0)
    parser.add_argument("--recompute_mates", action="store_true",
                       help="Re-run PyMOL and compare with cached mates")

    args = parser.parse_args()

    processed_dir = Path(args.processed_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Find all cache files
    cache_files = sorted(processed_dir.glob("*.pt"))
    logger.info(f"Found {len(cache_files)} cache files")

    # Sample for detailed analysis
    if args.num_samples < len(cache_files):
        sample_files = np.random.choice(cache_files, args.num_samples, replace=False)
    else:
        sample_files = cache_files

    # Statistics
    all_stats = []

    logger.info("\n" + "="*80)
    logger.info("SYMMETRY MATE QC ANALYSIS")
    logger.info("="*80)

    for cache_path in tqdm(sample_files, desc="Analyzing samples"):
        cache_key = cache_path.stem
        parts = cache_key.split('_')
        pdb_id = parts[0]

        # Load cached data
        cached = torch.load(cache_path, weights_only=False)

        # Analyze mate distances
        stats = analyze_mate_distances(cached, cutoff=args.cutoff)
        stats['pdb_id'] = cache_key

        # Visualize
        visualize_mates(cached, cache_key, output_dir)

        # Optionally recompute mates
        if args.recompute_mates:
            pdb_path = Path(args.base_pdb_dir) / pdb_id / f"{pdb_id}_final.pdb"
            if pdb_path.exists():
                comparison = compare_mate_detection(pdb_path, cache_path, args.cutoff)
                stats.update(comparison)

        all_stats.append(stats)

    # Create summary report
    df = pd.DataFrame(all_stats)

    logger.info("\n" + "="*80)
    logger.info("SUMMARY STATISTICS")
    logger.info("="*80)

    logger.info(f"\nTotal structures analyzed: {len(df)}")
    logger.info(f"\nStructures with mates: {(df['num_mates'] > 0).sum()} ({(df['num_mates'] > 0).sum() / len(df) * 100:.1f}%)")
    logger.info(f"Structures without mates: {(df['num_mates'] == 0).sum()}")

    if (df['num_mates'] > 0).any():
        mate_df = df[df['num_mates'] > 0]
        logger.info(f"\nFor structures WITH mates:")
        logger.info(f"  Number of mate atoms: {mate_df['num_mates'].describe()}")
        logger.info(f"\n  Distance to nearest ASU atom (Å):")
        logger.info(f"    Min: {mate_df['min_dist'].min():.2f}")
        logger.info(f"    Max: {mate_df['max_dist'].max():.2f}")
        logger.info(f"    Mean: {mate_df['mean_dist'].mean():.2f}")
        logger.info(f"    Median: {mate_df['median_dist'].median():.2f}")
        logger.info(f"\n  Percent of mates within cutoff ({args.cutoff}Å): {mate_df['percent_within_cutoff'].mean():.1f}%")

        # Check for issues
        logger.warning(f"\n⚠️  POTENTIAL ISSUES:")
        far_mates = mate_df[mate_df['min_dist'] > args.cutoff]
        if len(far_mates) > 0:
            logger.info(f"  {len(far_mates)} structures have mates farther than cutoff:")
            for _, row in far_mates.iterrows():
                logger.info(f"    {row['pdb_id']}: min_dist = {row['min_dist']:.2f}Å")

    if args.recompute_mates and 'match' in df.columns:
        logger.info(f"\n MATE RECOMPUTATION CHECK:")
        logger.info(f"  Matches cached: {df['match'].sum()} / {len(df)}")
        if not df['match'].all():
            logger.warning(f"  ⚠️  MISMATCHES FOUND:")
            mismatches = df[~df['match']]
            for _, row in mismatches.iterrows():
                logger.info(f"    {row['pdb_id']}: cached={row['cached_num_mates']}, fresh={row['fresh_num_mates']}")

    # Save report
    report_path = output_dir / "mate_qc_report.csv"
    df.to_csv(report_path, index=False)
    logger.info(f"\n✓ Full report saved to {report_path}")

    # Save summary plot
    if (df['num_mates'] > 0).any():
        fig, axes = plt.subplots(2, 2, figsize=(12, 10))

        # Number of mates histogram
        axes[0, 0].hist(df['num_mates'], bins=30, edgecolor='black')
        axes[0, 0].set_xlabel('Number of mate atoms')
        axes[0, 0].set_ylabel('Count')
        axes[0, 0].set_title('Distribution of Mate Atoms')

        # Distance to ASU
        mate_df = df[df['num_mates'] > 0]
        axes[0, 1].hist(mate_df['min_dist'], bins=30, edgecolor='black')
        axes[0, 1].axvline(args.cutoff, color='red', linestyle='--', label=f'Cutoff ({args.cutoff}Å)')
        axes[0, 1].set_xlabel('Min distance to ASU (Å)')
        axes[0, 1].set_ylabel('Count')
        axes[0, 1].set_title('Mate-ASU Distances')
        axes[0, 1].legend()

        # Percent within cutoff
        axes[1, 0].hist(mate_df['percent_within_cutoff'], bins=30, edgecolor='black')
        axes[1, 0].set_xlabel('% mates within cutoff')
        axes[1, 0].set_ylabel('Count')
        axes[1, 0].set_title('Mates Within Cutoff Distribution')

        # ASU vs Mate size
        axes[1, 1].scatter(mate_df['num_asu'], mate_df['num_mates'], alpha=0.6)
        axes[1, 1].set_xlabel('Number of ASU atoms')
        axes[1, 1].set_ylabel('Number of mate atoms')
        axes[1, 1].set_title('ASU Size vs Mate Size')

        plt.tight_layout()
        summary_plot_path = output_dir / "mate_qc_summary.png"
        plt.savefig(summary_plot_path, dpi=150, bbox_inches='tight')
        logger.info(f"✓ Summary plot saved to {summary_plot_path}")

    logger.info("\n" + "="*80)
    logger.info("QC COMPLETE")
    logger.info("="*80)


if __name__ == "__main__":
    main()
