name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'figures/**'
      - '.gitignore'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    # Skip CI if 'skip ci' is in the latest commit message (only relevant for push/pull_request triggers)
    # if: "!contains(github.event.head_commit.message, 'skip ci')"
    # Will add back on skipping for draft PRs too.
    # if: |
    #   !contains(github.event.head_commit.message, 'skip ci') &&
    #   (github.event_name != 'pull_request' || !github.event.pull_request.draft)

    steps:
      - uses: actions/checkout@v6

      - name: Setup UV
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.6"

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run tests
        env:
          TEST_DATA_DIR: ${{ github.workspace }}/tests/test_files
        run: uv run pytest tests/ --cov=src --cov-report=html --cov-report=term-missing --cov-fail-under=70
